"""Initial database setup

Revision ID: 54e815394bf2
Revises: 
Create Date: 2025-11-16 13:37:18.043635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54e815394bf2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('history', 'perc_text',
               existing_type=sa.VARCHAR(length=20, collation='Cyrillic_General_CI_AS'),
               type_=sa.String(length=40),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('history', 'perc_text',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=20, collation='Cyrillic_General_CI_AS'),
               existing_nullable=True)
    # ### end Alembic commands ###
